# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='usr2',
        ),
    ]
