# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_usuarios_usr2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.Usuarios'),
        ),
    ]
