# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_dispositivos_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivos',
            old_name='fecha',
            new_name='Nombre',
        ),
    ]
