# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-21 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_auto_20161203_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='city',
            field=models.CharField(default='Mexico', max_length=255),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=(1.0, 1.0), max_length=63),
        ),
    ]
